
const PROCESS_STATUS = {
	INVITED: 'INVITED',
	ASSIGNED: 'ASSIGNED',
	ACCEPTED: 'ACCEPTED',
	DECLINED: 'DECLINED',
	SUBMITTED: 'SUBMITTED',
	VIEWED: 'VIEWED',
	UNREGISTERED: 'UNREGISTERED',
	REGISTERED: 'REGISTERED',
};
module.exports = PROCESS_STATUS;
